name: CI
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgmp-dev
    - name: Run CI script
      run: ./ci.sh
  windows:
    runs-on: windows-2019
    steps:
      - name: 'Disable `autocrlf` in Git'
        run: git config --global core.autocrlf false
      - uses: actions/checkout@v3
      - name: Install MoSML
        run: |
          New-Item -ItemType Directory -Path C:\mosml -Force
          Invoke-WebRequest -Uri https://dbohdan.com/dist/mosml-2.10.1-win32.7z -OutFile C:\mosml\mosml.7z
          7z x -oC:\mosml C:\mosml\mosml.7z
      - name: Build initool
        run: .\build.cmd /batch /package
      - name: Check that initool runs
        run: .\initool.exe version
      - name: Add artifact filename to env
        run: |
          $artifact = Get-ChildItem -Filter *.zip | Select-Object -First 1
          Write-Output "artifactName=$($artifact.Basename)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          7z x -y $artifact
      - name: Upload Win32 binary
        uses: actions/upload-artifact@v3
        with:
          name: '${{ env.artifactName }}'
          path: |
            camlrt.dll
            initool.exe
