name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libgmp-dev
    - name: Run CI script
      run: ./ci.sh
